- hosts: localhost
  connection: local
  vars:
    git_clone_destination_path: "/tmp/policies"
    policy_as_code_add_or_update_policy_url: "http://opa-opa.apps.pawaro.eastus.aroapp.io/v1/policies/"
    git_repo_https_clone_url: "https://{{ git_user | urlencode }}:{{ git_password | urlencode }}@dev.azure.com/pepsico-ansible-poc/pepsico-ansible-pac/_git/policies"

    file_name_from_filepath_regex: '[^\\\/]+(?=\.[\w]+$)|[^\\\/]+$/'
  tasks:
    - name: Create empty policies folder
      file:
        path: "{{ git_clone_destination_path }}"
        state: directory
        mode: 0755
    - name: Clone policies Git repo
      git:
        repo: "{{ git_repo_https_clone_url }}"
        dest: "{{ git_clone_destination_path }}"
        clone: yes
        force: yes
        single_branch: yes
        version: main
    - name: Send each policy file to the policies validation server
      uri:
        url: "{{ policy_as_code_add_or_update_policy_url + ( item | regex_search(file_name_from_filepath_regex) ) }}"
        method: PUT
        body: "{{ lookup('file', item) }}"
        body_format: json
      when: "'_test.rego' not in item"
      check_mode: no
      with_fileglob:
       - "{{ git_clone_destination_path }}/policies/*.rego"