- hosts: localhost
  connection: local
  vars:
    rule_id: "/subscriptions/3c844226-48ad-4269-a9c9-2789e385b249/resourceGroups/aro-poc1/providers/Microsoft.Network/networkSecurityGroups/cognos-analytics-nsg/securityRules/Port_8080"
    new_protocol: "Tcp"
  tasks:
    - name: Parse rule ID for resource group & security group
      ansible.builtin.set_fact:
        resource_group: "{{ rule_id | regex_search(resource_group_query) | split('/') | last }}"
        security_group_name: "{{ rule_id | regex_search(security_group_query) | split('/') | last }}"
      vars:
        resource_group_query: "resourceGroups\\/[^\\/]+"
        security_group_query: "networkSecurityGroups\\/[^\\/]+"

    - name: get info about security group & rule
      azure.azcollection.azure_rm_securitygroup_info:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group_name }}"
      register: network_security_groups

    - name: Filter targeted NSG & rule
      ansible.builtin.set_fact:
        network_security_group: "{{ network_security_groups.securitygroups[0] }}"
        security_group_rule: "{{ network_security_groups | community.general.json_query(rule_query) | first }}"
      vars:
        rule_query: "securitygroups[0].rules[?id=='{{ rule_id }}']"

    - name: update NSG rule to use selected protocol type
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group_name }}"
        rules:
          - name: "{{ security_group_rule.name }}"
            protocol: "{{ new_protocol }}"
            priority: "{{ security_group_rule.priority }}"
            access: "{{ security_group_rule.access }}"
            description: "{{ security_group_rule.description }}"
            destination_address_prefix: "{{ security_group_rule.destination_address_prefix }}"
            destination_port_range: "{{ security_group_rule.destination_port_range }}"
            direction: "{{ security_group_rule.direction }}"
            source_address_prefix: "{{ security_group_rule.source_address_prefix }}"
            source_port_range: "{{ security_group_rule.source_port_range }}"